### ISSUE TITLE
local topology not present 

### ISSUE THREAD

**Issue by cwhitty** [Spirent/iTest-assets#26]
https://github.com/Spirent/iTest-assets/blob/850b8523f7393e25fba75ea7d12e8a9db11e75f2/Automation/Community/ai_spirent_demo_assets/test_cases/velocity/traffic/counter_accuracy_verification.fftc#L22

this test case refers to a topology that does not exist in the project

**Comment by alexorr** [comment]
Assets in the community folder are as-is, so do we want to police these kinds of errors?

**Comment by cwhitty** [comment]
corrected, changed local topology to one that exists in the project
